SECTION TEXT
C_OUTPUT TESTE_OFFSET+1
S_INPUT STRING+1, 100
S_OUTPUT STRING+1, 100
C_OUTPUT TESTE_OFFSET+2
STOP
SECTION DATA
TESTE_OFFSET: CONST 0
MENSAGEM: CONST 62
ENTER: CONST 10
SECTION BSS
STRING: SPACE 101
